### ISSUE TITLE
Gamerules of world not getting saved

### ISSUE THREAD

**Issue by CerialPvP** [InfernalSuite/AdvancedSlimePaper#75] opened 2023-09-30 20:44 UTC
**Describe the issue**
Basically, if you set gamerules for the world, it does not save, even with /save-all.

**Spigot version**
1.20.1 (Build from September 14th)

**Plugin version**
2.10.0

**How to reproduce**
Just apply a gamerule (like doDaylightCycle), restart the server, and boom.

**Crash reports (if available)**

**Comment by Askarionn** [comment] 2024-03-07 04:03
it's not a bug, aswm doesn't save gamerules

**Comment by kyngs** [comment] 2024-05-18 19:44
This is a feature, not a bug.

Duplicate of #45

**Closed by kyngs** 2024-05-18 19:44 UTC
Labels: bug
