### ISSUE TITLE
When the slime world is reloaded then blocks will stop updating when entering the world

### ISSUE THREAD

**Issue by wlm1455925277** [InfernalSuite/AdvancedSlimePaper#106] opened 2024-04-09 10:26 UTC
Describe the issue

When I use redstone in a slime world, reloading the world causes the redstone to stop updating and the lava to stop updating as well.

Spigot version

[18:14:41 INFO]: This server is running SlimeWorldManager version git-SlimeWorldManager-15816 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: cd684e7 on paper_upstream)
Unknown version
Previous version: git-SlimeWorldManager-31 (MC: 1.20.4)

Plugin version

[18:15:09 INFO]: SlimeWorldManager version 2.10.0
[18:15:09 INFO]: Advanced Slime World Manager is a resource that implements the Slime Region Format, designed by the Hypixel Team to load and save worlds more efficiently.
[18:15:09 INFO]: Authors: Grinderwolf, Paul19988, Jools, SoapTurtle, Gerolmed, b0ykoe, Owen and ComputerNerd100

How to reproduce

Build a redstone looper in the slime world and then reload the slime world

Crash reports (if available)

No
![2024-04-09_18 19 43](https://github.com/InfernalSuite/AdvancedSlimePaper/assets/87473483/1e9f6707-879d-4041-8464-a422292c9e07)

![2024-04-09_18 19 47](https://github.com/InfernalSuite/AdvancedSlimePaper/assets/87473483/3a39a3a2-74c7-4384-9f64-c121c4adfbdf)

**Comment by kyngs** [comment] 2024-04-09 10:27
How exactly are you reloading the world?

**Comment by emmanuelvlad** [comment] 2024-04-09 12:36
Related to https://github.com/InfernalSuite/AdvancedSlimePaper/issues/5

**Comment by kyngs** [comment] 2024-05-22 19:26
Closing as a duplicate of #5

**Closed by kyngs** 2024-05-22 19:26 UTC
Labels: bug
